/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BoxContainer {
        /**
          * Optional box title
         */
        "boxTitle"?: string;
    }
}
declare global {
    interface HTMLBoxContainerElement extends Components.BoxContainer, HTMLStencilElement {
    }
    var HTMLBoxContainerElement: {
        prototype: HTMLBoxContainerElement;
        new (): HTMLBoxContainerElement;
    };
    interface HTMLElementTagNameMap {
        "box-container": HTMLBoxContainerElement;
    }
}
declare namespace LocalJSX {
    interface BoxContainer {
        /**
          * Optional box title
         */
        "boxTitle"?: string;
    }
    interface IntrinsicElements {
        "box-container": BoxContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "box-container": LocalJSX.BoxContainer & JSXBase.HTMLAttributes<HTMLBoxContainerElement>;
        }
    }
}
