/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BoxContainer {
        /**
          * Optional box title
         */
        "boxTitle"?: string;
    }
    interface TitleBox {
        /**
          * Optional box sub title
         */
        "boxSubTitle"?: string;
        /**
          * Box title
         */
        "boxTitle": string;
    }
}
declare global {
    interface HTMLBoxContainerElement extends Components.BoxContainer, HTMLStencilElement {
    }
    var HTMLBoxContainerElement: {
        prototype: HTMLBoxContainerElement;
        new (): HTMLBoxContainerElement;
    };
    interface HTMLTitleBoxElement extends Components.TitleBox, HTMLStencilElement {
    }
    var HTMLTitleBoxElement: {
        prototype: HTMLTitleBoxElement;
        new (): HTMLTitleBoxElement;
    };
    interface HTMLElementTagNameMap {
        "box-container": HTMLBoxContainerElement;
        "title-box": HTMLTitleBoxElement;
    }
}
declare namespace LocalJSX {
    interface BoxContainer {
        /**
          * Optional box title
         */
        "boxTitle"?: string;
    }
    interface TitleBox {
        /**
          * Optional box sub title
         */
        "boxSubTitle"?: string;
        /**
          * Box title
         */
        "boxTitle"?: string;
    }
    interface IntrinsicElements {
        "box-container": BoxContainer;
        "title-box": TitleBox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "box-container": LocalJSX.BoxContainer & JSXBase.HTMLAttributes<HTMLBoxContainerElement>;
            "title-box": LocalJSX.TitleBox & JSXBase.HTMLAttributes<HTMLTitleBoxElement>;
        }
    }
}
